export enum NotificationType {
  TASK_PUBLISHED = 'TASK_PUBLISHED',
  TASK_CANCELLED = 'TASK_CANCELLED',
  TASK_JOINED = 'TASK_JOINED',
  SUBMISSION_RECEIVED = 'SUBMISSION_RECEIVED',
  SUBMISSION_APPROVED = 'SUBMISSION_APPROVED',
  SUBMISSION_REJECTED = 'SUBMISSION_REJECTED',
  VERIFICATION_COMPLETED = 'VERIFICATION_COMPLETED',
  ESCROW_LOCKED = 'ESCROW_LOCKED',
  ESCROW_RELEASED = 'ESCROW_RELEASED',
  ESCROW_REFUNDED = 'ESCROW_REFUNDED',
}
