import React, { useState } from 'react';
import { useAppStore } from '../../store/useAppStore';
import { motion, AnimatePresence } from 'framer-motion';
import { Sparkles, X, Cpu, DollarSign, Clock, Users, ShieldCheck, ArrowRight } from 'lucide-react';

export const CreateTaskModal: React.FC = () => {
  const { isCreateModalOpen, setIsCreateModalOpen, createTask } = useAppStore();
  const [prompt, setPrompt] = useState('');
  const [isAiAnalyzing, setIsAiAnalyzing] = useState(false);
  
  // Parsed fields
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [reward, setReward] = useState('35.0');
  const [workers, setWorkers] = useState('3');
  const [category, setCategory] = useState<'AI Verification' | 'Code Debugging' | 'Design Feedback' | 'Translation' | 'Local Knowledge' | 'Data Labeling'>('AI Verification');

  const handleAiParse = () => {
    if (!prompt.trim()) return;
    setIsAiAnalyzing(true);
    setTimeout(() => {
      setTitle(prompt.length > 50 ? prompt.slice(0, 48) + '...' : prompt);
      setDescription(`Task generated from prompt: "${prompt}". Requires human verification and consensus output.`);
      setReward((Math.floor(Math.random() * 60) + 20).toFixed(1));
      setWorkers('3');
      setIsAiAnalyzing(false);
    }, 600);
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!title) return;

    createTask({
      title: title || prompt,
      description: description || prompt,
      reward: `${reward} MON`,
      rewardNum: parseFloat(reward),
      duration: '10 mins',
      workersRequired: parseInt(workers, 10),
      category,
      difficulty: 'Medium',
      creator: '0x71C...9B41 (You)',
      aiVerified: true,
    });

    setIsCreateModalOpen(false);
    setPrompt('');
    setTitle('');
  };

  if (!isCreateModalOpen) return null;

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md">
        <motion.div
          initial={{ opacity: 0, scale: 0.95, y: 20 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.95, y: 20 }}
          className="liquid-glass rounded-3xl p-6 sm:p-8 max-w-2xl w-full border border-white/20 bg-black/90 text-white shadow-2xl relative"
        >
          {/* Header */}
          <div className="flex items-center justify-between pb-4 border-b border-white/10">
            <div className="flex items-center gap-2">
              <div className="w-8 h-8 rounded-full bg-[#836EF9]/20 text-[#836EF9] flex items-center justify-center border border-[#836EF9]/30">
                <Sparkles className="w-4 h-4" />
              </div>
              <div>
                <h3 className="text-base font-semibold text-white">Create Task with AI</h3>
                <p className="text-xs text-white/50">Describe what you need in plain English</p>
              </div>
            </div>
            <button
              onClick={() => setIsCreateModalOpen(false)}
              className="text-white/40 hover:text-white transition-colors p-1"
            >
              <X className="w-5 h-5" />
            </button>
          </div>

          <form onSubmit={handleSubmit} className="mt-6 space-y-6">
            {/* Natural Prompt Input */}
            <div>
              <label className="text-xs font-mono text-white/60 mb-2 block uppercase tracking-wider">
                What do you need done?
              </label>
              <div className="relative">
                <textarea
                  rows={3}
                  value={prompt}
                  onChange={(e) => setPrompt(e.target.value)}
                  placeholder="e.g. Verify legal clause in contract generated by Claude 3.7 or inspect retail storefront in Tokyo..."
                  className="w-full bg-[#111113] border border-white/15 rounded-2xl p-4 text-sm text-white placeholder-white/30 focus:outline-none focus:border-[#836EF9] transition-all resize-none"
                />
                <button
                  type="button"
                  onClick={handleAiParse}
                  className="absolute right-3 bottom-3 text-xs bg-white/10 hover:bg-white/20 text-white px-3 py-1.5 rounded-xl border border-white/10 transition-colors flex items-center gap-1.5 font-mono"
                >
                  <Cpu className="w-3.5 h-3.5 text-[#836EF9]" />
                  <span>Auto-Fill Specs</span>
                </button>
              </div>
            </div>

            {/* AI Generated Specs Preview */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label className="text-xs font-mono text-white/60 mb-1 block">Task Title</label>
                <input
                  type="text"
                  value={title}
                  onChange={(e) => setTitle(e.target.value)}
                  placeholder="Title of microtask"
                  className="w-full bg-[#111113] border border-white/15 rounded-xl px-3.5 py-2.5 text-xs text-white focus:outline-none focus:border-[#836EF9]"
                />
              </div>

              <div>
                <label className="text-xs font-mono text-white/60 mb-1 block">Category</label>
                <select
                  value={category}
                  onChange={(e) => setCategory(e.target.value as any)}
                  className="w-full bg-[#111113] border border-white/15 rounded-xl px-3.5 py-2.5 text-xs text-white focus:outline-none focus:border-[#836EF9]"
                >
                  <option value="AI Verification">AI Verification</option>
                  <option value="Code Debugging">Code Debugging</option>
                  <option value="Translation">Translation</option>
                  <option value="Local Knowledge">Local Knowledge</option>
                  <option value="Design Feedback">Design Feedback</option>
                  <option value="Data Labeling">Data Labeling</option>
                </select>
              </div>

              <div>
                <label className="text-xs font-mono text-white/60 mb-1 block">Reward (MON)</label>
                <div className="relative">
                  <input
                    type="number"
                    value={reward}
                    onChange={(e) => setReward(e.target.value)}
                    className="w-full bg-[#111113] border border-white/15 rounded-xl pl-3.5 pr-12 py-2.5 text-xs text-white focus:outline-none focus:border-[#836EF9]"
                  />
                  <span className="absolute right-3 top-2.5 text-xs font-mono text-[#836EF9] font-bold">MON</span>
                </div>
              </div>

              <div>
                <label className="text-xs font-mono text-white/60 mb-1 block">Workers Required</label>
                <input
                  type="number"
                  value={workers}
                  onChange={(e) => setWorkers(e.target.value)}
                  className="w-full bg-[#111113] border border-white/15 rounded-xl px-3.5 py-2.5 text-xs text-white focus:outline-none focus:border-[#836EF9]"
                />
              </div>
            </div>

            {/* Actions */}
            <div className="pt-4 border-t border-white/10 flex items-center justify-between">
              <div className="text-xs text-white/50 font-mono flex items-center gap-1.5">
                <ShieldCheck className="w-4 h-4 text-emerald-400" />
                <span>Monad Smart Contract Escrow Lock</span>
              </div>

              <div className="flex items-center gap-3">
                <button
                  type="button"
                  onClick={() => setIsCreateModalOpen(false)}
                  className="px-4 py-2 text-xs text-white/60 hover:text-white transition-colors"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="bg-white text-black font-semibold text-xs rounded-full px-6 py-2.5 hover:bg-white/90 transition-all flex items-center gap-1.5 shadow-lg"
                >
                  <span>Publish & Lock Escrow</span>
                  <ArrowRight className="w-3.5 h-3.5" />
                </button>
              </div>
            </div>
          </form>
        </motion.div>
      </div>
    </AnimatePresence>
  );
};
