export type TaskStatus = 'DRAFT' | 'PUBLISHED' | 'ACCEPTED' | 'IN_PROGRESS' | 'SUBMITTED' | 'VERIFIED' | 'COMPLETED' | 'REJECTED';

export type SubmissionType =
  | 'text'
  | 'multiple_choice'
  | 'rating'
  | 'file'
  | 'checklist';

export type VerificationType =
  | 'AI Verification'
  | 'Creator Review'
  | 'AI First'
  | 'Consensus'
  | 'Hybrid';

export interface TaskItem {
  id: string;
  title: string;
  description: string;
  instructions?: string;
  requirements?: string;
  reward: string; // e.g. "25.0 MON"
  rewardNum: number;
  duration: string;
  workersRequired: number;
  workersJoined: number;
  workersCompleted: number;
  category: 'AI Verification' | 'Code Debugging' | 'Design Feedback' | 'Translation' | 'Local Knowledge' | 'Data Labeling';
  difficulty: 'Easy' | 'Medium' | 'Hard';
  creator: string;
  status: TaskStatus;
  submissionType: SubmissionType;
  verificationType: VerificationType;
  options?: string[]; // for multiple choice
  createdAt: string;
  userSubmission?: any;
  aiSummary?: {
    overallSentiment: string;
    topFeedback: string[];
    commonProblems: string[];
    suggestions: string[];
    consensusScore: number;
  };
}

export interface TransactionItem {
  id: string;
  txHash: string;
  type: 'Task Reward' | 'Task Escrow' | 'AI Audit Fee' | 'Refund';
  amount: string;
  taskTitle: string;
  status: 'CONFIRMED' | 'PENDING';
  timestamp: string;
  taskId?: string;
}

export const USE_CASES = [
  {
    title: 'AI Verification & Red-Teaming',
    description: 'Human-in-the-loop validation for LLM edge cases, hallucination checking, and ethical safety audits.',
    category: 'AI Safety',
    rewardAvg: '40-100 MON',
    speed: '< 3 mins',
  },
  {
    title: 'Real-World Intelligence',
    description: 'On-the-ground verification, store hours check, physical inspections, and local context gathering worldwide.',
    category: 'Physical Computing',
    rewardAvg: '50-200 MON',
    speed: '< 15 mins',
  },
  {
    title: 'Instant Code Debugging',
    description: 'Micro-tasked code reviews, memory leak diagnosis, and security vulnerability inspection by human experts.',
    category: 'Engineering',
    rewardAvg: '80-300 MON',
    speed: '< 10 mins',
  },
  {
    title: 'Cultural & Idiomatic Translation',
    description: 'Nuanced human translation that captures emotional context, humor, and local slang that AI misses.',
    category: 'Localization',
    rewardAvg: '20-60 MON',
    speed: '< 5 mins',
  },
  {
    title: 'UX & Product Feedback',
    description: 'Rapid user feedback, micro-surveys, and accessibility testing across different browsers and devices.',
    category: 'Product Research',
    rewardAvg: '30-90 MON',
    speed: '< 8 mins',
  },
  {
    title: 'Multimodal Data Annotation',
    description: 'High-precision labeling for audio, thermal satellite, and 3D point cloud training datasets.',
    category: 'Machine Learning',
    rewardAvg: '60-180 MON',
    speed: '< 12 mins',
  },
];

export const INITIAL_TASKS: TaskItem[] = [
  {
    id: 'task-101',
    title: 'Audit Claude 3.7 Output for Hallucination in Legal Contract',
    description: 'Review a 3-page NDA generated by Claude 3.7. Verify section 4 indemnification clause against California law compliance.',
    instructions: '1. Read section 4.2 of attached NDA.\n2. Cross-reference California Civil Code § 1668.\n3. Flag any ambiguous liability waivers.',
    requirements: 'Must have legal or compliance auditing background.',
    reward: '45.0 MON',
    rewardNum: 45.0,
    duration: '10 mins',
    workersRequired: 20,
    workersJoined: 18,
    workersCompleted: 15,
    category: 'AI Verification',
    difficulty: 'Medium',
    creator: '0x71C...9B41 (Agent-0X)',
    status: 'PUBLISHED',
    submissionType: 'text',
    verificationType: 'AI Verification',
    createdAt: '2 mins ago',
    aiSummary: {
      overallSentiment: 'Positive (88% Agreement)',
      topFeedback: ['Indemnification clause is compliant with § 1668', 'Clear liability bounds'],
      commonProblems: ['Vague definition of trade secrets in section 2.1'],
      suggestions: ['Add explicit arbitration governing clause'],
      consensusScore: 94.2,
    },
  },
  {
    id: 'task-102',
    title: 'Verify Physical Storefront & Hours in Shibuya, Tokyo',
    description: 'Take high-resolution photos of retail storefront at 3-12-1 Jinan and confirm current business opening hours.',
    instructions: '1. Walk to location.\n2. Capture storefront sign with GPS location tag enabled.\n3. Note printed store hours.',
    reward: '80.0 MON',
    rewardNum: 80.0,
    duration: '15 mins',
    workersRequired: 5,
    workersJoined: 4,
    workersCompleted: 3,
    category: 'Local Knowledge',
    difficulty: 'Easy',
    creator: '0x3A2...81F0 (MapData Inc)',
    status: 'PUBLISHED',
    submissionType: 'file',
    verificationType: 'Creator Review',
    createdAt: '5 mins ago',
    aiSummary: {
      overallSentiment: 'Verified (100% Match)',
      topFeedback: ['Photo geotag matches 3-12-1 Jinan exactly', 'Store sign clearly visible'],
      commonProblems: ['Minor reflection on glass sign'],
      suggestions: ['Store open hours updated to 10:00 - 21:00'],
      consensusScore: 98.0,
    },
  },
  {
    id: 'task-103',
    title: 'Select Most Trustworthy & High-Converting Logo Concept',
    description: 'Compare 3 AI-generated brand logos for a Web3 security startup. Pick the most professional concept.',
    instructions: 'Review all 3 logo concepts and vote on the design that conveys maximum security and trust.',
    reward: '25.0 MON',
    rewardNum: 25.0,
    duration: '3 mins',
    workersRequired: 50,
    workersJoined: 42,
    workersCompleted: 40,
    category: 'Design Feedback',
    difficulty: 'Easy',
    creator: '0x99A...12D9 (DevSwarm)',
    status: 'PUBLISHED',
    submissionType: 'multiple_choice',
    verificationType: 'Consensus',
    options: ['Concept A (Shield Gradient)', 'Concept B (Geometric Node)', 'Concept C (Minimalist Shield)'],
    createdAt: '8 mins ago',
    aiSummary: {
      overallSentiment: 'Strong Preference for Concept A',
      topFeedback: ['Concept A shield gradient feels modern & secure', 'Concept C feels too generic'],
      commonProblems: ['Concept B icon does not scale well to 16px favicon'],
      suggestions: ['Adopt Concept A with solid dark stroke border'],
      consensusScore: 91.5,
    },
  },
  {
    id: 'task-104',
    title: 'Japanese Idiomatic Translation & Nuance Review for Landing Page',
    description: 'Review localized hero headline for B2B SaaS landing page in Tokyo market. Ensure natural, authoritative tone.',
    instructions: 'Evaluate headline "AI Workflow Engine" localized translation and suggest 2 natural Japanese equivalents.',
    reward: '30.0 MON',
    rewardNum: 30.0,
    duration: '5 mins',
    workersRequired: 10,
    workersJoined: 8,
    workersCompleted: 6,
    category: 'Translation',
    difficulty: 'Easy',
    creator: '0x1F4...88E1 (GlobalizeAI)',
    status: 'PUBLISHED',
    submissionType: 'text',
    verificationType: 'AI First',
    createdAt: '12 mins ago',
  },
  {
    id: 'task-105',
    title: 'Rate Mobile UX Checkout Flow on iOS Safari',
    description: 'Test keyboard navigation and screen reader compatibility for mobile Web3 wallet modal on iOS Safari.',
    instructions: '1. Open test URL on mobile Safari.\n2. Complete mock transaction.\n3. Provide 1-5 rating and detailed feedback.',
    reward: '60.0 MON',
    rewardNum: 60.0,
    duration: '12 mins',
    workersRequired: 15,
    workersJoined: 9,
    workersCompleted: 7,
    category: 'Design Feedback',
    difficulty: 'Medium',
    creator: '0x88B...33C9 (MonadLabs)',
    status: 'PUBLISHED',
    submissionType: 'rating',
    verificationType: 'Creator Review',
    createdAt: '15 mins ago',
  },
  {
    id: 'task-106',
    title: 'Record Screen Testing Monad DEX Swap & Slippage Settings',
    description: 'Record a short 30-second screen recording showing custom slippage settings adjustment on DEX testnet.',
    instructions: 'Record screen while attempting a 5 MON swap with 0.5% custom slippage.',
    reward: '95.0 MON',
    rewardNum: 95.0,
    duration: '8 mins',
    workersRequired: 8,
    workersJoined: 3,
    workersCompleted: 2,
    category: 'Code Debugging',
    difficulty: 'Medium',
    creator: '0x55E...77A2 (GeoAI)',
    status: 'PUBLISHED',
    submissionType: 'file',
    verificationType: 'Hybrid',
    createdAt: '22 mins ago',
  },
];

export const INITIAL_TRANSACTIONS: TransactionItem[] = [
  {
    id: 'tx-1',
    txHash: '0x8f2a...91e4',
    type: 'Task Reward',
    amount: '+45.0 MON',
    taskTitle: 'Audit Claude 3.7 Output for Hallucination in Legal Contract',
    status: 'CONFIRMED',
    timestamp: '10 mins ago',
    taskId: 'task-101',
  },
  {
    id: 'tx-2',
    txHash: '0x3c1d...4b88',
    type: 'Task Escrow',
    amount: '-150.0 MON',
    taskTitle: 'Debug Rust Warp Socket Connection Timeout on Heavy Load',
    status: 'CONFIRMED',
    timestamp: '2 hours ago',
    taskId: 'task-103',
  },
  {
    id: 'tx-3',
    txHash: '0x71e9...22a1',
    type: 'Task Reward',
    amount: '+80.0 MON',
    taskTitle: 'Verify Physical Storefront & Hours in Shibuya, Tokyo',
    status: 'CONFIRMED',
    timestamp: '1 day ago',
    taskId: 'task-102',
  },
];
