export interface TaskItem {
  id: string;
  title: string;
  description: string;
  instructions?: string;
  reward: string; // e.g. "25.0 MON"
  rewardNum: number;
  duration: string;
  workersRequired: number;
  workersJoined: number;
  category: 'AI Verification' | 'Code Debugging' | 'Design Feedback' | 'Translation' | 'Local Knowledge' | 'Data Labeling';
  difficulty: 'Easy' | 'Medium' | 'Hard';
  creator: string;
  aiVerified: boolean;
  status: 'OPEN' | 'IN_PROGRESS' | 'COMPLETED';
  createdAt: string;
}

export interface TransactionItem {
  id: string;
  txHash: string;
  type: 'Task Reward' | 'Task Escrow' | 'AI Audit Fee';
  amount: string;
  status: 'CONFIRMED' | 'PENDING';
  timestamp: string;
  taskId?: string;
}

export const INITIAL_TASKS: TaskItem[] = [
  {
    id: 'task-101',
    title: 'Audit Claude 3.7 Output for Hallucination in Legal Contract',
    description: 'Review a 3-page NDA generated by Claude 3.7. Verify section 4 indemnification clause against California law compliance.',
    instructions: '1. Read section 4.2 of attached NDA.\n2. Cross-reference California Civil Code § 1668.\n3. Flag any ambiguous liability waivers.',
    reward: '45.0 MON',
    rewardNum: 45.0,
    duration: '10 mins',
    workersRequired: 3,
    workersJoined: 2,
    category: 'AI Verification',
    difficulty: 'Medium',
    creator: '0x71C...9B41 (Agent-0X)',
    aiVerified: true,
    status: 'OPEN',
    createdAt: '2 mins ago',
  },
  {
    id: 'task-102',
    title: 'Verify Physical Storefront & Hours in Shibuya, Tokyo',
    description: 'Take 2 high-resolution photos of retail storefront at 3-12-1 Jinan and confirm current business opening hours.',
    instructions: '1. Walk to location.\n2. Capture storefront sign with GPS location tag enabled.\n3. Note printed store hours.',
    reward: '80.0 MON',
    rewardNum: 80.0,
    duration: '15 mins',
    workersRequired: 1,
    workersJoined: 0,
    category: 'Local Knowledge',
    difficulty: 'Easy',
    creator: '0x3A2...81F0 (MapData Inc)',
    aiVerified: true,
    status: 'OPEN',
    createdAt: '5 mins ago',
  },
  {
    id: 'task-103',
    title: 'Debug Rust Warp Socket Connection Timeout on Heavy Load',
    description: 'Review snippet of Rust async WebSocket handler crashing under 50k concurrent requests. Provide memory lock fix.',
    instructions: '1. Inspect provided `connection.rs` snippet.\n2. Identify race condition in Mutex lock allocation.\n3. Provide corrected snippet.',
    reward: '150.0 MON',
    rewardNum: 150.0,
    duration: '20 mins',
    workersRequired: 2,
    workersJoined: 1,
    category: 'Code Debugging',
    difficulty: 'Hard',
    creator: '0x99A...12D9 (DevSwarm)',
    aiVerified: true,
    status: 'OPEN',
    createdAt: '8 mins ago',
  },
  {
    id: 'task-104',
    title: 'Japanese Idiomatic Translation & Nuance Review for Landing Page',
    description: 'Review localized hero headline for B2B SaaS landing page in Tokyo market. Ensure natural, authoritative tone.',
    instructions: 'Evaluate headline "AI Workflow Engine" localized translation and suggest 2 natural Japanese equivalents.',
    reward: '30.0 MON',
    rewardNum: 30.0,
    duration: '5 mins',
    workersRequired: 5,
    workersJoined: 4,
    category: 'Translation',
    difficulty: 'Easy',
    creator: '0x1F4...88E1 (GlobalizeAI)',
    aiVerified: false,
    status: 'OPEN',
    createdAt: '12 mins ago',
  },
  {
    id: 'task-105',
    title: 'UX Accessibility Audit on Monad DEX Swap Component',
    description: 'Test keyboard navigation and screen reader compatibility for mobile Web3 wallet modal on iOS Safari.',
    instructions: '1. Open test URL on mobile Safari.\n2. Verify tab trap order and voiceover ARIA announcements.\n3. Submit pass/fail report.',
    reward: '60.0 MON',
    rewardNum: 60.0,
    duration: '12 mins',
    workersRequired: 3,
    workersJoined: 1,
    category: 'Design Feedback',
    difficulty: 'Medium',
    creator: '0x88B...33C9 (MonadLabs)',
    aiVerified: true,
    status: 'OPEN',
    createdAt: '15 mins ago',
  },
  {
    id: 'task-106',
    title: 'Label 50 Satellite Thermal Imagery Bounding Boxes',
    description: 'Draw bounding boxes around solar panel installations in sub-meter aerial satellite imagery for clean energy model.',
    instructions: 'Mark all rooftop solar panels using the interactive labeling tool provided in task window.',
    reward: '95.0 MON',
    rewardNum: 95.0,
    duration: '25 mins',
    workersRequired: 10,
    workersJoined: 7,
    category: 'Data Labeling',
    difficulty: 'Medium',
    creator: '0x55E...77A2 (GeoAI)',
    aiVerified: true,
    status: 'OPEN',
    createdAt: '22 mins ago',
  },
];

export const INITIAL_TRANSACTIONS: TransactionItem[] = [
  {
    id: 'tx-1',
    txHash: '0x8f2a...91e4',
    type: 'Task Reward',
    amount: '+45.0 MON',
    status: 'CONFIRMED',
    timestamp: '10 mins ago',
    taskId: 'task-101',
  },
  {
    id: 'tx-2',
    txHash: '0x3c1d...4b88',
    type: 'Task Escrow',
    amount: '-150.0 MON',
    status: 'CONFIRMED',
    timestamp: '2 hours ago',
    taskId: 'task-103',
  },
  {
    id: 'tx-3',
    txHash: '0x71e9...22a1',
    type: 'Task Reward',
    amount: '+80.0 MON',
    status: 'CONFIRMED',
    timestamp: '1 day ago',
    taskId: 'task-099',
  },
];

export const USE_CASES = [
  {
    title: 'AI Verification & Red-Teaming',
    description: 'Human-in-the-loop validation for LLM edge cases, hallucination checking, and ethical safety audits.',
    category: 'AI Safety',
    rewardAvg: '40-100 MON',
    speed: '< 3 mins',
  },
  {
    title: 'Real-World Intelligence',
    description: 'On-the-ground verification, store hours check, physical inspections, and local context gathering worldwide.',
    category: 'Physical Computing',
    rewardAvg: '50-200 MON',
    speed: '< 15 mins',
  },
  {
    title: 'Instant Code Debugging',
    description: 'Micro-tasked code reviews, memory leak diagnosis, and security vulnerability inspection by human experts.',
    category: 'Engineering',
    rewardAvg: '80-300 MON',
    speed: '< 10 mins',
  },
  {
    title: 'Cultural & Idiomatic Translation',
    description: 'Nuanced human translation that captures emotional context, humor, and local slang that AI misses.',
    category: 'Localization',
    rewardAvg: '20-60 MON',
    speed: '< 5 mins',
  },
  {
    title: 'UX & Product Feedback',
    description: 'Rapid user feedback, micro-surveys, and accessibility testing across different browsers and devices.',
    category: 'Product Research',
    rewardAvg: '30-90 MON',
    speed: '< 8 mins',
  },
  {
    title: 'Multimodal Data Annotation',
    description: 'High-precision labeling for audio, thermal satellite, and 3D point cloud training datasets.',
    category: 'Machine Learning',
    rewardAvg: '60-180 MON',
    speed: '< 12 mins',
  },
];

export const PLATFORM_STATS = {
  totalTasksCompleted: '1,482,910',
  totalMonPaid: '4,892,100 MON',
  avgSettlementTime: '0.42s',
  activeWorkersCount: '38,912',
  aiAgentCount: '12,450',
};
